## NUMPY

In [2]:
'''important library in python
1.numpy
2.pandas
3.seaborn

Numpy : It is a core numerical computing package in python.
        its core type is np array also known as numpy array.
        
1. it is used in all numerical computation in python.
2. it provides high dimenson datastructures like array,vectors,matrix etc.
3. it is implemented in c and fortan thus it is much faster.
4. to use numpy we have to import the module
'''
import numpy as np

In [4]:
# initialising the numpy array 
# array is a function of numpy array.
# it the bracket we'll input a list
np1= np.array([1,2,3,4])
print(type(np1))

<class 'numpy.ndarray'>


In [6]:
print(np1)

[1 2 3 4]


In [10]:
# to create a matrix we'll pass 2 list (nested list)
mat1=np.array([[1,2],[3,4]])
print(type(mat1))
print(mat1)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [12]:
## np1 -> 1D array  mat1 -> 2D array
## to know the shape of the array 

print(np1.shape)
print(mat1.shape)

(4,)
(2, 2)


In [14]:
# unlike python list where you have many different types of elemet 
# here we can use only one type of element.

# to get the type of element of array
print(mat1.dtype)

int32


In [16]:
#changing an element of the matrix
mat1[0,0]=5
print(mat1)

[[5 2]
 [3 4]]


In [18]:
#In list we use the functn range to generate element in the sequence
# here we use the functon arange to generate the element.

mat2=np.arange(0,10,1) #prints the element from start till n-1.
print(mat2)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# if we want to include both i.e starting point and ending point 
# use linspace function.
# here np.linspace(starting,ending,no of elements)
mat3=np.linspace(0,10,20)
print(mat3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:
mat3.shape # it is a 1d array

(20,)

In [22]:
# to generate a random matrix
# use np.random.rand(no of rows,no of col)
mat4=np.random.rand(5,5)
print(mat4)#it contains random numbers between 0 and 1.

[[0.0689612  0.93740319 0.72201897 0.25944037 0.01350632]
 [0.50680016 0.58388673 0.86381623 0.64557562 0.86153047]
 [0.15022584 0.02327307 0.41858944 0.96854177 0.10554736]
 [0.19588422 0.14429082 0.38079981 0.81149554 0.46611231]
 [0.98509123 0.4505051  0.97190859 0.87933336 0.48976259]]


In [23]:
# for getting a normally distributed random numbers
mat5=np.random.randn(5,5)
print(mat5)

[[ 1.38501245 -1.44209689  1.50602978  1.2405887  -0.87628308]
 [-0.54706268  0.94579963 -0.32935598  0.5070602   0.52729512]
 [-0.64873868 -1.66313227 -0.15885447  1.33055785 -1.37062528]
 [ 0.52418862 -0.04730556  1.02979281 -0.12114247  0.00787871]
 [ 2.05898554 -0.82537637  0.1305701  -1.73009921 -0.26503885]]


In [28]:
# to create a diagonal matrix
mat6=np.diag([18,4,8]) #given the diagonal elements
print(mat6)

[[18  0  0]
 [ 0  4  0]
 [ 0  0  8]]


In [37]:
# zero matrix in which all the elements are zeros
mat7=np.zeros((10,2)) #creates a zero matrix of 10 rows and 2 columns
print(mat7)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [39]:
# one matrix in which all the elements are ones
mat7=np.ones((10,2)) #creates a ones matrix of 10 rows and 2 columns
print(mat7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [42]:
# here we can also use slicising.
print(mat5[0,0])#gives the zeroth element
print(mat5[3,4])# gives the element of 3rd row 4th column

1.3850124457770283
0.007878705428946019


In [43]:
print(mat5[0:3:])# we'll get all the values till 2nd row

[[ 1.38501245 -1.44209689  1.50602978  1.2405887  -0.87628308]
 [-0.54706268  0.94579963 -0.32935598  0.5070602   0.52729512]
 [-0.64873868 -1.66313227 -0.15885447  1.33055785 -1.37062528]]
